# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.

# The CMake executable.
CMAKE_COMMAND = /data/data/ru.iiec.cxxdroid/files/bin/cmake

# The command to remove a file.
RM = /data/data/ru.iiec.cxxdroid/files/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /storage/emulated/0/Documents/Cxxdroid/Mystic-Gems

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /storage/emulated/0/Documents/Cxxdroid/Mystic-Gems

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/data/data/ru.iiec.cxxdroid/files/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Cxxdroid/Mystic-Gems/CMakeFiles /storage/emulated/0/Documents/Cxxdroid/Mystic-Gems//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /storage/emulated/0/Documents/Cxxdroid/Mystic-Gems/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Mystic-Gems

# Build rule for target.
Mystic-Gems: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Mystic-Gems
.PHONY : Mystic-Gems

# fast build rule for target.
Mystic-Gems/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/build
.PHONY : Mystic-Gems/fast

src/About.o: src/About.cpp.o
.PHONY : src/About.o

# target to build an object file
src/About.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/About.cpp.o
.PHONY : src/About.cpp.o

src/About.i: src/About.cpp.i
.PHONY : src/About.i

# target to preprocess a source file
src/About.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/About.cpp.i
.PHONY : src/About.cpp.i

src/About.s: src/About.cpp.s
.PHONY : src/About.s

# target to generate assembly for a file
src/About.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/About.cpp.s
.PHONY : src/About.cpp.s

src/Button.o: src/Button.cpp.o
.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i
.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s
.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/ColorIndex.o: src/ColorIndex.cpp.o
.PHONY : src/ColorIndex.o

# target to build an object file
src/ColorIndex.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ColorIndex.cpp.o
.PHONY : src/ColorIndex.cpp.o

src/ColorIndex.i: src/ColorIndex.cpp.i
.PHONY : src/ColorIndex.i

# target to preprocess a source file
src/ColorIndex.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ColorIndex.cpp.i
.PHONY : src/ColorIndex.cpp.i

src/ColorIndex.s: src/ColorIndex.cpp.s
.PHONY : src/ColorIndex.s

# target to generate assembly for a file
src/ColorIndex.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ColorIndex.cpp.s
.PHONY : src/ColorIndex.cpp.s

src/ComboText.o: src/ComboText.cpp.o
.PHONY : src/ComboText.o

# target to build an object file
src/ComboText.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ComboText.cpp.o
.PHONY : src/ComboText.cpp.o

src/ComboText.i: src/ComboText.cpp.i
.PHONY : src/ComboText.i

# target to preprocess a source file
src/ComboText.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ComboText.cpp.i
.PHONY : src/ComboText.cpp.i

src/ComboText.s: src/ComboText.cpp.s
.PHONY : src/ComboText.s

# target to generate assembly for a file
src/ComboText.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ComboText.cpp.s
.PHONY : src/ComboText.cpp.s

src/Cursor.o: src/Cursor.cpp.o
.PHONY : src/Cursor.o

# target to build an object file
src/Cursor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Cursor.cpp.o
.PHONY : src/Cursor.cpp.o

src/Cursor.i: src/Cursor.cpp.i
.PHONY : src/Cursor.i

# target to preprocess a source file
src/Cursor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Cursor.cpp.i
.PHONY : src/Cursor.cpp.i

src/Cursor.s: src/Cursor.cpp.s
.PHONY : src/Cursor.s

# target to generate assembly for a file
src/Cursor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Cursor.cpp.s
.PHONY : src/Cursor.cpp.s

src/ElementGUI.o: src/ElementGUI.cpp.o
.PHONY : src/ElementGUI.o

# target to build an object file
src/ElementGUI.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ElementGUI.cpp.o
.PHONY : src/ElementGUI.cpp.o

src/ElementGUI.i: src/ElementGUI.cpp.i
.PHONY : src/ElementGUI.i

# target to preprocess a source file
src/ElementGUI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ElementGUI.cpp.i
.PHONY : src/ElementGUI.cpp.i

src/ElementGUI.s: src/ElementGUI.cpp.s
.PHONY : src/ElementGUI.s

# target to generate assembly for a file
src/ElementGUI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/ElementGUI.cpp.s
.PHONY : src/ElementGUI.cpp.s

src/Font.o: src/Font.cpp.o
.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i
.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s
.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/Fragment.o: src/Fragment.cpp.o
.PHONY : src/Fragment.o

# target to build an object file
src/Fragment.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Fragment.cpp.o
.PHONY : src/Fragment.cpp.o

src/Fragment.i: src/Fragment.cpp.i
.PHONY : src/Fragment.i

# target to preprocess a source file
src/Fragment.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Fragment.cpp.i
.PHONY : src/Fragment.cpp.i

src/Fragment.s: src/Fragment.cpp.s
.PHONY : src/Fragment.s

# target to generate assembly for a file
src/Fragment.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Fragment.cpp.s
.PHONY : src/Fragment.cpp.s

src/Game.o: src/Game.cpp.o
.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i
.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s
.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Gem.o: src/Gem.cpp.o
.PHONY : src/Gem.o

# target to build an object file
src/Gem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Gem.cpp.o
.PHONY : src/Gem.cpp.o

src/Gem.i: src/Gem.cpp.i
.PHONY : src/Gem.i

# target to preprocess a source file
src/Gem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Gem.cpp.i
.PHONY : src/Gem.cpp.i

src/Gem.s: src/Gem.cpp.s
.PHONY : src/Gem.s

# target to generate assembly for a file
src/Gem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Gem.cpp.s
.PHONY : src/Gem.cpp.s

src/Instructions.o: src/Instructions.cpp.o
.PHONY : src/Instructions.o

# target to build an object file
src/Instructions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Instructions.cpp.o
.PHONY : src/Instructions.cpp.o

src/Instructions.i: src/Instructions.cpp.i
.PHONY : src/Instructions.i

# target to preprocess a source file
src/Instructions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Instructions.cpp.i
.PHONY : src/Instructions.cpp.i

src/Instructions.s: src/Instructions.cpp.s
.PHONY : src/Instructions.s

# target to generate assembly for a file
src/Instructions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Instructions.cpp.s
.PHONY : src/Instructions.cpp.s

src/Layout.o: src/Layout.cpp.o
.PHONY : src/Layout.o

# target to build an object file
src/Layout.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Layout.cpp.o
.PHONY : src/Layout.cpp.o

src/Layout.i: src/Layout.cpp.i
.PHONY : src/Layout.i

# target to preprocess a source file
src/Layout.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Layout.cpp.i
.PHONY : src/Layout.cpp.i

src/Layout.s: src/Layout.cpp.s
.PHONY : src/Layout.s

# target to generate assembly for a file
src/Layout.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Layout.cpp.s
.PHONY : src/Layout.cpp.s

src/MainMenu.o: src/MainMenu.cpp.o
.PHONY : src/MainMenu.o

# target to build an object file
src/MainMenu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/MainMenu.cpp.o
.PHONY : src/MainMenu.cpp.o

src/MainMenu.i: src/MainMenu.cpp.i
.PHONY : src/MainMenu.i

# target to preprocess a source file
src/MainMenu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/MainMenu.cpp.i
.PHONY : src/MainMenu.cpp.i

src/MainMenu.s: src/MainMenu.cpp.s
.PHONY : src/MainMenu.s

# target to generate assembly for a file
src/MainMenu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/MainMenu.cpp.s
.PHONY : src/MainMenu.cpp.s

src/SoundManager.o: src/SoundManager.cpp.o
.PHONY : src/SoundManager.o

# target to build an object file
src/SoundManager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/SoundManager.cpp.o
.PHONY : src/SoundManager.cpp.o

src/SoundManager.i: src/SoundManager.cpp.i
.PHONY : src/SoundManager.i

# target to preprocess a source file
src/SoundManager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/SoundManager.cpp.i
.PHONY : src/SoundManager.cpp.i

src/SoundManager.s: src/SoundManager.cpp.s
.PHONY : src/SoundManager.s

# target to generate assembly for a file
src/SoundManager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/SoundManager.cpp.s
.PHONY : src/SoundManager.cpp.s

src/Textures.o: src/Textures.cpp.o
.PHONY : src/Textures.o

# target to build an object file
src/Textures.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Textures.cpp.o
.PHONY : src/Textures.cpp.o

src/Textures.i: src/Textures.cpp.i
.PHONY : src/Textures.i

# target to preprocess a source file
src/Textures.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Textures.cpp.i
.PHONY : src/Textures.cpp.i

src/Textures.s: src/Textures.cpp.s
.PHONY : src/Textures.s

# target to generate assembly for a file
src/Textures.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Textures.cpp.s
.PHONY : src/Textures.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/Window.o: src/Window.cpp.o
.PHONY : src/Window.o

# target to build an object file
src/Window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Window.cpp.o
.PHONY : src/Window.cpp.o

src/Window.i: src/Window.cpp.i
.PHONY : src/Window.i

# target to preprocess a source file
src/Window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Window.cpp.i
.PHONY : src/Window.cpp.i

src/Window.s: src/Window.cpp.s
.PHONY : src/Window.s

# target to generate assembly for a file
src/Window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/Window.cpp.s
.PHONY : src/Window.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Mystic-Gems.dir/build.make CMakeFiles/Mystic-Gems.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Mystic-Gems"
	@echo "... src/About.o"
	@echo "... src/About.i"
	@echo "... src/About.s"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/ColorIndex.o"
	@echo "... src/ColorIndex.i"
	@echo "... src/ColorIndex.s"
	@echo "... src/ComboText.o"
	@echo "... src/ComboText.i"
	@echo "... src/ComboText.s"
	@echo "... src/Cursor.o"
	@echo "... src/Cursor.i"
	@echo "... src/Cursor.s"
	@echo "... src/ElementGUI.o"
	@echo "... src/ElementGUI.i"
	@echo "... src/ElementGUI.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/Fragment.o"
	@echo "... src/Fragment.i"
	@echo "... src/Fragment.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Gem.o"
	@echo "... src/Gem.i"
	@echo "... src/Gem.s"
	@echo "... src/Instructions.o"
	@echo "... src/Instructions.i"
	@echo "... src/Instructions.s"
	@echo "... src/Layout.o"
	@echo "... src/Layout.i"
	@echo "... src/Layout.s"
	@echo "... src/MainMenu.o"
	@echo "... src/MainMenu.i"
	@echo "... src/MainMenu.s"
	@echo "... src/SoundManager.o"
	@echo "... src/SoundManager.i"
	@echo "... src/SoundManager.s"
	@echo "... src/Textures.o"
	@echo "... src/Textures.i"
	@echo "... src/Textures.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/Window.o"
	@echo "... src/Window.i"
	@echo "... src/Window.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

